name: Run Telegram Bot

on:
  schedule:
    - cron: "*/15 * * * *"  # هر 15 دقیقه یک بار اجرا می‌شود
  push:
    branches:
      - main  # اجرا هنگام push به شاخه main
  workflow_dispatch:  # امکان اجرای دستی در GitHub Actions

concurrency:
  group: telegram-bot
  cancel-in-progress: true  # اگر job قبلی هنوز در حال اجراست، آن را متوقف کن

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # دریافت کدهای پروژه

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # استفاده از نسخه پایدار پایتون

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Run Python script with Secret
        env:
          API_KEY: ${{ secrets.BOT_KEY }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          BOT_ID: ${{ secrets.BOT_ID }}
          LINKS_KEY: ${{ secrets.LINKS_ID }}
        run: python main.py  # اجرا کردن اسکریپت اصلی

      - name: Commit and Push Database
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add users.db
          git commit -m "Update SQLite database (users.db)" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
